trigger: none

parameters:
  - name: subject_area
    displayName: Subject area
    type: string
    values:
      - "01"
      - "02"
      - "03"
  - name: environment
    displayName: environment
    type: string
    values:
      - "dev"
      - "qa"
      - "prod"

jobs:
  - job: terraform
    pool: "Default"
    steps:
      - task: TerraformInstaller@1 # Task must be installed from Marketplace
        inputs:
          terraformVersion: "1.10.5"
      - script: |
          terraform init
        workingDirectory: "${{ parameters.subject_area}}/{{ parameters.environment }}"
      - script: |
          terraform fmt
        workingDirectory: "${{ parameters.subject_area}}/{{ parameters.environment }}"
      - script: |
          terraform plan -out=tf.plan
        workingDirectory: "${{ parameters.subject_area}}/{{ parameters.environment }}"
      - script: |
          terraform apply tf.plan
        workingDirectory: "${{ parameters.subject_area}}/{{ parameters.environment }}"
