trigger: none

variables:
  - group: "udp-assessment"

parameters:
  - name: subject_area
    displayName: Subject area
    type: string
    values:
      - "01"
      - "02"
      - "03"
  - name: environment
    displayName: environment
    type: string
    values:
      - "dev"
      - "qa"
      - "prod"

jobs:
  - job: terraform
    pool: "Default"
    variables:
      ARM_CLIENT_ID: $(SERVICE_PRINCIPAL_ID)
      ARM_CLIENT_SECRET: $(SERVICE_PRINCIPAL_SECRET)
      ARM_TENANT_ID: $(TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      TF_VAR_subscription_id: $(SUBSCRIPTION_ID)
    steps:
      - task: TerraformInstaller@1 # Task must be installed from Marketplace
        inputs:
          terraformVersion: "1.10.5"
      - script: |
          terraform init
        workingDirectory: "${{ parameters.subject_area}}/${{ parameters.environment }}"
      - script: |
          terraform fmt
        workingDirectory: "${{ parameters.subject_area}}/${{ parameters.environment }}"
      - script: |
          terraform plan -out=tf.plan
        workingDirectory: "${{ parameters.subject_area}}/${{ parameters.environment }}"
      - script: |
          terraform apply tf.plan && terraform destroy --auto-approve
        workingDirectory: "${{ parameters.subject_area}}/${{ parameters.environment }}"
